version: '3.3'

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx.Dockerfile
        ports:
            - 3000:80
        depends_on:
            - fpm
    fpm:
        build:
            context: .
            dockerfile: docker/fpm.Dockerfile
        volumes:
            - ./:/var/www/nazirov-tagaev-fp-admin
        links:
            - mysql
    mysql:
        image: mysql/mysql-server
        container_name: mysql-db
        restart: unless-stopped
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: mailings
            MYSQL_USER: admin
            MYSQL_PASSWORD_FILE: /run/secrets/db_password
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        secrets:
            - db_password
            - db_root_password

secrets:
    db_password:
        file: ./secrets/db_password.txt
    db_root_password:
        file: ./secrets/db_root_password.txt
